"""update_user_type_enum

Revision ID: d6931f2ae8eb
Revises: b4df4g2285b6
Create Date: 2025-12-08 15:32:13.194105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6931f2ae8eb'
down_revision: Union[str, None] = 'b4df4g2285b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passengers', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否为用户本人的默认乘车人',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passengers', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否为用户本人的默认乘车人',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###

